### ISSUE TITLE
Issue with observations_stamped.hpp when trying to buld package

### ISSUE THREAD

**Issue by s350462** [ptrmu/fiducial_vlam_sam#10]
Hello. When I try to build the package with colcon build, the following occurs:
/home/flock2_ws/src/fiducial_vlam_sam/fiducial_vlam/src/vdet_node.cpp:4:10: fatal error: fiducial_vlam_msgs/msg/observations_stamped.hpp: No such file or directory
 #include "fiducial_vlam_msgs/msg/observations_stamped.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/vdet_main.dir/src/vdet_node.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/vlocx_node.dir/src/calibrate.cpp.o] Error 1
make[1]: *** [CMakeFiles/vlocx_node.dir/all] Error 2
make[2]: *** [CMakeFiles/vlocx_main.dir/src/calibrate.cpp.o] Error 1
/home/flock2_ws/src/fiducial_vlam_sam/fiducial_vlam/src/vloc_node.cpp:11:10: fatal error: fiducial_vlam_msgs/msg/observations_stamped.hpp: No such file or directory
 #include "fiducial_vlam_msgs/msg/observations_stamped.hpp"
 I am trying to build it for the Eloquent distribution. Could you please help me? Thank you.

**Comment by ptrmu** [comment]
Hi Angelos,

I am slowly working on this project in my spare time. I am excited by it and think it has potential but it has not been polished for others to use at this point. Currently I am working in foxy and I can’t remember how I left the eloquent branch.

fiducial_vlam_msgs is a module in the fiducial_vlam_sam project. It should be automatically built by colcon before fiducial_vlam. Maybe the dependencies in my package.xml are incorrect or maybe the build is set up incorrectly. Did you type the command “source install/setup.bash” ?

The project ptrmu/fiducial_vlam is older and doesn’t use GTSAM. It is more reliable but unfortunately has no documentation.

Sorry,
peter

From: s350462 ***@***.***>
Sent: Sunday, March 21, 2021 3:07 PM
To: ptrmu/fiducial_vlam_sam ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ptrmu/fiducial_vlam_sam] Issue with observations_stamped.hpp when trying to buld package (#10)


Hello. When I try to build the package with colcon build, the following occurs:
/home/angelos/flock2_ws/src/fiducial_vlam_sam/fiducial_vlam/src/vdet_node.cpp:4:10: fatal error: fiducial_vlam_msgs/msg/observations_stamped.hpp: No such file or directory
#include "fiducial_vlam_msgs/msg/observations_stamped.hpp"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/vdet_main.dir/src/vdet_node.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/vlocx_node.dir/src/calibrate.cpp.o] Error 1
make[1]: *** [CMakeFiles/vlocx_node.dir/all] Error 2
make[2]: *** [CMakeFiles/vlocx_main.dir/src/calibrate.cpp.o] Error 1
/home/angelos/flock2_ws/src/fiducial_vlam_sam/fiducial_vlam/src/vloc_node.cpp:11:10: fatal error: fiducial_vlam_msgs/msg/observations_stamped.hpp: No such file or directory
#include "fiducial_vlam_msgs/msg/observations_stamped.hpp"
I am trying yo build it for the Eloquent distribution. Could you please help me? Thank you.

**Comment by s350462** [comment]
No problem at all. Thank you so much! I will install Foxy and try again. ( And yes it is a pretty cool project!)
