### ISSUE TITLE
Dictionary initialized before parameters are loaded

### ISSUE THREAD

**Issue by clydemcqueen** [ptrmu/fiducial_vlam_sam#7]
The dictionary object is initialized before parameters are loaded, so setting the parameter `loc_aruco_dictionary_id` to something other than 0 has no effect.

https://github.com/ptrmu/fiducial_vlam_sam/blob/e2497a0fc52a040f2266ffa2e0854729a6019423/fiducial_vlam/src/fiducial_math.cpp#L79

My workaround (for now) is to set the default value of `loc_aruco_dictionary_id` to 8 in `vloc_context.hpp`.

**Comment by ptrmu** [comment]
I have checked in a fix for this.

**Comment by ptrmu** [comment]
Thanks for pointing this problem out!
